import { PROJECT_NAME } from '../App/constants'

export const COMPONENT_NAME = 'CreateElectionPage';

export const CHANGE_TOKEN_COUNT = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_TOKEN_COUNT';
export const CHANGE_TOKEN_VALID_IN_DAYS = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_TOKEN_VALID_IN_DAYS';

export const GENERATE_TOKENS = PROJECT_NAME + '/' + COMPONENT_NAME + '/GENERATE_TOKENS';
export const GENERATE_TOKENS_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/GENERATE_TOKENS_SUCCESS';
export const GENERATE_TOKENS_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/GENERATE_TOKENS_ERROR';

export const FETCH_ACTUAL_TOKENS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ACTUAL_TOKENS';
export const FETCH_ACTUAL_TOKENS_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ACTUAL_TOKENS_SUCCESS';
export const FETCH_ACTUAL_TOKENS_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ACTUAL_TOKENS_ERROR';
