package pl.krakow.up.upvote.core.model.exceptions;

public class VotePollConstants {

    public static final String ERROR_VOTE_POLL_NAME_NULL = "ERROR_VOTE_POLL_NAME_NULL";
    public static final String ERROR_USER_USERNAME_INVALID_LENGTH = "ERROR_USER_USERNAME_INVALID_LENGTH";
    public static final String ERROR_USER_EMAIL_NULL = "ERROR_USER_EMAIL_NULL";
    public static final String ERROR_USER_EMAIL_INVALID_FORMAT = "ERROR_USER_EMAIL_INVALID_FORMAT";
    public static final String ERROR_USER_EMAIL_ALREADY_EXISTS = "ERROR_USER_EMAIL_ALREADY_EXISTS";
    public static final String ERROR_USER_PASSWORD_HASH_NULL = "ERROR_USER_PASSWORD_HASH_NULL";
    public static final String ERROR_USER_FIRST_NAME_NULL = "ERROR_USER_FIRST_NAME_NULL";
    public static final String ERROR_USER_FIRST_NAME_INVALID_LENGTH = "ERROR_USER_FIRST_NAME_INVALID_LENGTH";
    public static final String ERROR_USER_LAST_NAME_NULL = "ERROR_USER_LAST_NAME_NULL";
    public static final String ERROR_USER_LAST_NAME_INVALID_LENGTH = "ERROR_USER_LAST_NAME_INVALID_LENGTH";
    public static final String ERROR_USER_NOT_EXIST = "ERROR_USER_NOT_EXIST";

    public static final String ERROR_VOTE_POLL_VALIDATION_FAILURE = "ERROR_VOTE_POLL_VALIDATION_FAILURE";

    public static final String ERROR_CREATE_USER_INVALID_REGISTRATION_CODE = "ERROR_CREATE_USER_INVALID_REGISTRATION_CODE";
    public static final String ERROR_CREATE_VOTE_POLL_FAILURE = "ERROR_CREATE_VOTE_POLL_FAILURE";

    public static final String ERROR_UPDATE_VOTE_POLL_FAILURE = "ERROR_UPDATE_VOTE_POLL_FAILURE";
}
