import { PROJECT_NAME } from '../App/constants'

export const COMPONENT_NAME = 'CreateElectionPage';


export const CHANGE_NAME = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_NAME';
export const CHANGE_DESCRIPTION = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_DESCRIPTION';
export const CHANGE_START_DATE = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_START_DATE';
export const CHANGE_END_DATE = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_END_DATE';
export const CHANGE_START_END_DATE = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_START_END_DATE';
export const CHANGE_PUBLISH_DATE = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_PUBLISH_DATE';
export const CHANGE_USER_QUERY_STRING = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_USER_QUERY_STRING';

export const ADD_SELECTED_USER = PROJECT_NAME + '/' + COMPONENT_NAME + '/ADD_SELECTED_USER';
export const REMOVE_SELECTED_USER = PROJECT_NAME + '/' + COMPONENT_NAME + '/REMOVE_SELECTED_USER';

export const CREATE_NEW_POLL = PROJECT_NAME + '/' + COMPONENT_NAME + '/CREATE_NEW_POLL';
export const CREATE_NEW_POLL_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/CREATE_NEW_POLL_SUCCESS';
export const CREATE_NEW_POLL_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/CREATE_NEW_POLL_ERROR';

export const FETCH_ALL_USERS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ALL_USERS';
export const FETCH_ALL_USERS_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ALL_USERS_ERROR';


export const FETCH_POLL_DETAILS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_POLL_DETAILS';
export const FETCH_POLL_DETAILS_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_POLL_DETAILS_SUCCESS';
export const FETCH_POLL_DETAILS_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_POLL_DETAILS_ERROR';

export const UPDATE_EXISTING_POLL = PROJECT_NAME + '/' + COMPONENT_NAME + '/UPDATE_EXISTING_POLL';
export const UPDATE_EXISTING_POLL_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/UPDATE_EXISTING_POLL_SUCCESS';
export const UPDATE_EXISTING_POLL_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/UPDATE_EXISTING_POLL_ERROR';

export const DELETE_POLL = PROJECT_NAME + '/' + COMPONENT_NAME + '/DELETE_POLL';
export const DELETE_POLL_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/DELETE_POLL_SUCCESS';
export const DELETE_POLL_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/DELETE_POLL_ERROR';
