/*
 * OrganizationPage constants
 */

import { PROJECT_NAME } from '../App/constants'

export const COMPONENT_NAME = 'OrganizationPage';
export const CHANGE_ORGANIZATION_ID = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_ORGANIZATION_ID';

export const LOAD_BASE_DATA = PROJECT_NAME + '/' + COMPONENT_NAME + '/LOAD_BASE_DATA';
export const LOAD_BASE_DATA_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/LOAD_BASE_DATA_SUCCESS';
export const LOAD_BASE_DATA_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/LOAD_BASE_DATA_ERROR';

export const LOAD_DETAIL_DATA = PROJECT_NAME + '/' + COMPONENT_NAME + '/LOAD_DETAIL_DATA';
export const LOAD_DETAIL_DATA_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/LOAD_DETAIL_DATA_SUCCESS';
export const LOAD_DETAIL_DATA_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/LOAD_DETAIL_DATA_ERROR';

