import { PROJECT_NAME } from '../App/constants'

export const COMPONENT_NAME = 'ProfilePage';


export const CHANGE_EMAIL = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_EMAIL';
export const CHANGE_FIRST_NAME = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_FIRST_NAME';
export const CHANGE_LAST_NAME = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_LAST_NAME';
export const CHANGE_USERNAME = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_USERNAME';
export const CHANGE_PASSWORD = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_REPEAT = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_PASSWORD_REPEAT';

export const EDIT_PROFILE = PROJECT_NAME + '/' + COMPONENT_NAME + '/EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/EDIT_PROFILE_ERROR';

export const FETCH_USER_DATA = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_USER_DATA';
export const FETCH_USER_DATA_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_USER_DATA_ERROR';
