import { PROJECT_NAME } from '../App/constants'

export const COMPONENT_NAME = 'BrowseElectionPage';


export const CHANGE_POLL_QUERY_STRING = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_POLL_QUERY_STRING';

export const FETCH_ALL_POLLS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ALL_POLLS';
export const FETCH_ALL_POLLS_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ALL_POLLS_SUCCESS';
export const FETCH_ALL_POLLS_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/FETCH_ALL_POLLS_ERROR';


export const SELECT_POLL_ROW = PROJECT_NAME + '/' + COMPONENT_NAME + '/SELECT_POLL_ROW';
export const CHANGE_CHB_CANDIDATE_SELECTION = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_CHB_CANDIDATE_SELECTION';
export const CLOSE_POLL_DETAILS = PROJECT_NAME + '/' + COMPONENT_NAME + '/CLOSE_POLL_DETAILS';

export const SEND_VOTES = PROJECT_NAME + '/' + COMPONENT_NAME + '/SEND_VOTES';
export const SEND_VOTES_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/SEND_VOTES_SUCCESS';
export const SEND_VOTES_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/SEND_VOTES_ERROR';
