import { PROJECT_NAME } from '../App/constants'

export const COMPONENT_NAME = 'LoginPage';

export const CHANGE_EMAIL = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_EMAIL';
export const CHANGE_PASSWORD = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_PASSWORD';
export const CLEAR_LOGIN_PAGE_DATA = PROJECT_NAME + '/' + COMPONENT_NAME + '/CLEAR_LOGIN_PAGE_DATA';

export const POST_LOGIN = PROJECT_NAME + '/' + COMPONENT_NAME + '/POST_LOGIN';
export const POST_LOGIN_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/POST_LOGIN_ERROR';
