import { PROJECT_NAME } from '../App/constants'

export const COMPONENT_NAME = 'RegisterPage';

export const CHANGE_REGISTRATION_CODE = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_REGISTRATION_CODE';
export const CHANGE_EMAIL = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_EMAIL';
export const CHANGE_FIRST_NAME = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_FIRST_NAME';
export const CHANGE_LAST_NAME = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_LAST_NAME';
export const CHANGE_PASSWORD = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_PASSWORD';
export const CHANGE_PASSWORD_REPEAT = PROJECT_NAME + '/' + COMPONENT_NAME + '/CHANGE_PASSWORD_REPEAT';
export const POST_NEW_USER = PROJECT_NAME + '/' + COMPONENT_NAME + '/POST_NEW_USER';
export const POST_NEW_USER_SUCCESS = PROJECT_NAME + '/' + COMPONENT_NAME + '/POST_NEW_USER_SUCCESS';
export const POST_NEW_USER_ERROR = PROJECT_NAME + '/' + COMPONENT_NAME + '/POST_NEW_USER_ERROR';
export const CLOSE_REGISTRATION_RESULT_MODAL = PROJECT_NAME + '/' + COMPONENT_NAME + '/CLOSE_REGISTRATION_RESULT_MODAL';

