version: '3'
services:
  upvote:
    image: "vote-backend:1"
    container_name: "vote-upVote"
    build: 
      context: ./upVote
      dockerfile: Dockerfile
    hostname: upVote
    ports:
      - "8080:8080"

      